services:
  # Servicio Web para la aplicación Flask
  - type: web
    name: contract-inspector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MAX_UPLOAD_SIZE_MB
        value: 16
      - key: DEBUG_MODE
        value: false
    healthCheckPath: /
    autoDeploy: true